# ==== PostgreSQL settings ====
spring.datasource.url=jdbc:postgresql://localhost:5432/mydemo
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driverClassName=org.postgresql.Driver

# ?????????????? ????????/?????????? ?????
# (? ?????????? ????? ?????? 'validate' ??? ?????????)
spring.jpa.hibernate.ddl-auto=update

# ?? ??????? ???????? SQL:
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ???? ?????????? (????? ??????)
server.port=8080
